import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import StoreImage from '@/components/StoreImage';
import ScrollReveal from '@/components/ScrollReveal';
import { contentMetadata } from '@/lib/seo';
import { scopedCss } from '@/lib/scoped-css';
import { redirectOr404 } from '@/lib/seo-navigation';
import { getCachedContentBySlug } from '@/lib/storefront-cache';
export const revalidate = 120;
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const entry = await getCachedContentBySlug('PAGE', slug); return entry ? contentMetadata(entry, 'page') : {}; }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const entry = await getCachedContentBySlug('PAGE', slug); if (!entry) return redirectOr404(`/${slug}`); if (entry.type !== 'PAGE' || entry.status !== 'PUBLISHED') notFound(); const customScope = `content-custom-${entry.id}`; const customStyle = scopedCss(entry.customCss, customScope); const schema = entry.schemaJson || { '@context': 'https://schema.org', '@type': entry.schemaType || 'WebPage', name: entry.title, description: entry.seoDescription || entry.excerpt || undefined }; return <main className="min-h-[70vh] bg-white pb-20 text-slate-700">{customStyle ? <style dangerouslySetInnerHTML={{ __html: customStyle }} /> : null}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }}/><section className="mx-auto max-w-[900px] px-4 pb-10 pt-16 text-center sm:px-6"><ScrollReveal><span className="text-[10px] font-semibold text-blue-600">SMMExpertService</span><h1 className="mx-auto mt-3 max-w-4xl text-[38px] font-bold tracking-[-0.045em] text-slate-950 sm:text-[52px]">{entry.title}</h1>{entry.excerpt ? <p className="mx-auto mt-5 max-w-2xl text-[11px] leading-6 text-slate-600">{entry.excerpt}</p> : null}</ScrollReveal></section><article className="mx-auto max-w-[1200px] px-4 py-8 sm:px-6"><div className="mx-auto max-w-[900px]">{entry.featuredImageUrl ? <ScrollReveal><div className="mb-10 overflow-hidden rounded-2xl bg-slate-100"><StoreImage src={entry.featuredImageUrl} alt={entry.title} width={1500} height={900} className="h-auto w-full object-cover"/></div></ScrollReveal> : null}<ScrollReveal delay={60}><div className={`rich-copy ${customScope} text-[14px] leading-7 text-slate-700 [&_a]:font-semibold [&_a]:text-blue-600 [&_a]:underline [&_blockquote]:my-7 [&_blockquote]:border-l-4 [&_blockquote]:border-blue-500 [&_blockquote]:bg-blue-50 [&_blockquote]:px-6 [&_blockquote]:py-4 [&_h2]:mb-4 [&_h2]:mt-10 [&_h2]:text-3xl [&_h2]:font-bold [&_h2]:text-slate-950 [&_h3]:mb-3 [&_h3]:mt-8 [&_h3]:text-2xl [&_h3]:font-bold [&_h3]:text-slate-950 [&_img]:my-8 [&_img]:rounded-2xl [&_li]:my-2 [&_ol]:my-5 [&_ol]:list-decimal [&_ol]:pl-6 [&_p]:my-5 [&_strong]:text-slate-950 [&_ul]:my-5 [&_ul]:list-disc [&_ul]:pl-6`} dangerouslySetInnerHTML={{ __html: entry.content }}/></ScrollReveal></div></article></main>; }
